<?php
$data=array(
	"allowed"=>false,
	"allowed_ips"=>array("::1","127.0.0.1"),
	"pass"=>"dgdfdfgdfg3t45335ytrhdsgsdgdfgfdgw3t53gefgfg",
	"setupmainuser"=>array(
		"allowed"=>true,
		"pass"=>"dfgdgfgdgfdfgdfgd435y4yj66grthykjykgzgdfgdg",
	)
);
?>
